CFLAGS=-ggdb -Wall -std=c11
LDLIBS=-lm

all: zadanie_0 zadanie_2 zadanie_1 zadanie_3 zadanie_4 zadanie_5 zadanie_6 zadanie_7 zadanie_8

clean :
	rm -f zadanie_0 zadanie_1 zadanie_2 zadanie_3 zadanie_4 zadanie_5 zadanie_6 zadanie_7 zadanie_8